version: "3"

services:
  tg_horde_ratings:
    container_name: horde_ratings_tg
    stdin_open: true
    tty: true
    command: python3 -m ratings
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      #- ALL_PROXY=http://127.0.0.1:3128
      - STABLEHORDE_KEY=0000000000
      - TELEGRAM_TOKEN=0000000000
